### ISSUE TITLE
Unable to use on Java versions earlier than 21

### ISSUE THREAD

**Issue by BluSpring** [FlorianMichael/AsmFabricLoader#10]
When trying to use this library on Java versions earlier than 21 (in my case, 17), Gradle will fail with the `Unsupported class file major version 65` error.

**Comment by FlorianMichael** [comment]
What Minecraft version are you using for the mod?

**Comment by BluSpring** [comment]
MC 1.20.1

**Comment by FlorianMichael** [comment]
Release `1.0.3` should work with Java 17 for now, I'll see if I can downgrade the java version.

**Comment by BluSpring** [comment]
In theory I think you should be able to lower the target compatibility to make it work with J17?

**Comment by FlorianMichael** [comment]
Can you try if `1.1.6-SNAPSHOT` works for you?

**Comment by BluSpring** [comment]
Jitpack doesn't seem to compile it, and it's not published on either Maven repos, so I'm gonna have to clone and local publish.

**Comment by BluSpring** [comment]
Loaded it in via mavenLocal, it seems like it loads, but prePrePreLaunch doesn't appear to be working.
![image](https://github.com/user-attachments/assets/9d0021d1-1bf3-44be-b10c-28b3ce6d9734)

**Comment by FlorianMichael** [comment]
Could you maybe provide your entrypoint class code and your fabric.mod.json?

**Comment by FlorianMichael** [comment]
Released `1.1.6` which should fix the issue, thank you for reporting.
